
construction = ['Owner Authorization',
'Bidding & Contract Documents',
'Plans',
'Spedifications',
'Addenda',
'Submittals',
'Shop Drawings',
'Bonds',
'Insurance Certificates',
'Design Clarifications',
'Baseline Schedule',
'Schedule Revisions',
'Permits',
'Meeting Minutes',
'Payment Requests',
'Correspondence',
'Progress Reports',
'Progress Photographs',
'Change Orders',
'Substantial Completion',
'Punch List - Final Completion',
'Certificate of Occupancy',
'Maintenance & Operating Manuals',
'Guarantees - Warrantees',
'As-Built Documents',
'Reporting',
'Budget']
