it = [
'Bidding & Contract Documents',
'Plans',
'Spedifications',
'Addenda',
'Submittals',
'Design Clarifications',
'Baseline Schedule',
'Schedule Revisions',
'Meeting Minutes',
'Payment Requests',
'Correspondence',
'Progress Reports',
'Progress Photographs',
'Change Orders',
'Substantial Completion',
'Maintenance & Operating Manuals',
'Guarantees - Warrantees',
'As-Built Documents']
